fix: use flock to prevent stale locks in ugreen-diskiomon.
- Fix an issue where the lockfile persists after
  ugreen-diskiomon.service stops, preventing subsequent service starts.
- Replace the existing lockfile mechanism with flock, which
  automatically releases the lock when the process exits or is
  terminated, eliminating the need for manual cleanup while ensuring
  exclusive execution.

diff --git a/scripts/ugreen-diskiomon b/scripts/ugreen-diskiomon
--- a/scripts/ugreen-diskiomon
+++ b/scripts/ugreen-diskiomon
@@ -1,10 +1,7 @@
 #!/usr/bin/bash
 
-# function for removing lockfile
+# function for cleanup
 exit-ugreen-diskiomon() {
-  if [[ -f "/var/run/ugreen-diskiomon.lock" ]]; then
-    rm "/var/run/ugreen-diskiomon.lock"
-  fi
   [[ -n "$smart_check_pid" ]] && kill $smart_check_pid 2>/dev/null
   [[ -n "$zpool_check_pid" ]] && kill $zpool_check_pid 2>/dev/null
   [[ -n "$disk_online_check_pid" ]] && kill $disk_online_check_pid 2>/dev/null
@@ -12,14 +9,14 @@ exit-ugreen-diskiomon() {
   exit 0
 }
 
-# check if script is already running
-if [[ -f "/var/run/ugreen-diskiomon.lock" ]]; then
+# acquire an exclusive lock
+exec 9>/run/ugreen-diskiomon.lock
+if ! flock -n 9; then
   echo "ugreen-diskiomon already running!"
   exit 1
 fi
-touch /var/run/ugreen-diskiomon.lock
 
-# trap exit and remove lockfile
+# trap exit and cleanup
 trap 'exit-ugreen-diskiomon' EXIT INT TERM
 
 # use variables from config file (unRAID specific)
